name: models
description: "Models for Civic24"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: "3.38.7"

dependencies:
  flutter:
    sdk: flutter
    
  # General Dependencies
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  uuid: ^4.5.0
  faker: ^2.2.0
  solar_icons: ^0.0.5
  cloud_firestore: ^6.1.2
  meta: ^1.15.0

  # Package Dependencies
  constants:
    path: ../constants
  localization:
    path: ../localization
  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Internal Packages
  rules:
    path: ../rules

  # Utility Packages
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
