name: services
description: "Services for Civic24"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: "3.38.7"

dependencies:
  flutter:
    sdk: flutter
  
  # Package Dependencies
  constants:
    path: ../constants
  models:
    path: ../models
  utils:
    path: ../utils
  localization:
    path: ../localization

  # State Management
  stacked: ^3.5.0
  stacked_services: ^1.6.0

  # General Dependencies
  permission_handler: ^11.4.0
  rxdart: ^0.28.0
  intl: ^0.20.2
  crypto: ^3.0.6
  logger: ^2.5.0
  hive_ce: ^2.10.1
  path_provider: ^2.1.5
  android_intent_plus: ^6.0.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  image_cropper: ^11.0.0  
  flutter_image_compress: ^2.4.0   
  exif: ^3.3.0
  app_settings: ^6.1.1
  flutter_local_notifications: ^19.0.0
  http: ^1.6.0
  http_parser: ^4.1.2
  mime: ^2.0.0

  # Google/Firebase Dependencies
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1
  firebase_analytics: ^12.1.1
  firebase_crashlytics: ^5.0.7
  firebase_storage: ^13.0.6
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

dependency_overrides:
  # This is a temporary fix pending the release of the next version of the stacked_generator package
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Internal Packages
  rules:
    path: ../rules

  # Utility Packages
  build_runner: ^2.7.1
  stacked_generator: ^2.0.0
  mockito: ^5.4.4


flutter:
  uses-material-design: true
