name: citizen
description: Citizen app for Civic24
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: "3.38.7"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  stacked: ^3.5.0
  stacked_services: ^1.6.0

  # Google/Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1
  firebase_analytics: ^12.1.1
  firebase_crashlytics: ^5.0.7
  firebase_storage: ^13.0.6
  cloud_firestore: ^6.1.2
  firebase_performance: ^0.11.1+4
  firebase_app_check: ^0.4.1+4

  # Internal Packages
  assets:
    path: ../../packages/assets
  components:
    path: ../../packages/components  
  constants:
    path: ../../packages/constants
  models:
    path: ../../packages/models
  localization:
    path: ../../packages/localization
  services:
    path: ../../packages/services
  styles:
    path: ../../packages/styles
  utils:
    path: ../../packages/utils

  # Utility Packages
  nigerian_states_and_lga: ^1.0.0
  country_state_city: ^0.1.6
  country_flags: ^3.3.0
  rxdart: ^0.28.0

  # UI Components
  solar_icons: ^0.0.5
  overlay_support: ^2.1.0
  flutter_animate: ^4.5.2
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Internal Packages
  rules:
    path: ../../packages/rules
    
  # Utility Packages
  build_runner: ^2.7.1
  stacked_generator: ^2.0.0
  mockito: ^5.4.4
  golden_toolkit: ^0.15.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  # change_app_package_name: ^1.5.0
  # rename: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/jpg/
    - assets/lottie/

flutter_gen:
  output: lib/ui/shared/src
  integrations:
    flutter_svg: true
