name: utils
description: "Utilities for Civic24"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: "3.38.7"

dependencies:
  flutter:
    sdk: flutter

  # General Dependencies
  platform: ^3.1.6
  email_validator: ^3.0.0
  intl: ^0.20.2
  logger: ^2.6.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0

  # Package Dependencies
  localization:
    path: ../localization
  models:
    path: ../models


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Internal Packages
  rules:
    path: ../rules
  stacked_generator: ^2.0.0

flutter:
  uses-material-design: true
